import {StyleSheet} from 'react-native';

const editClassStyles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'white',
        borderRadius:20,
    },
    title:{
        flex:0.1,
        justifyContent:'center',
        alignItems:'center'
    },
    checkBox:{
        flex:0.80,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    line:{
        borderWidth:0.5,
        borderColor:'black'
    },
    dateContainer:{
        flex:0.3,
    },
    classTypeContainer:{
        flex:0.07, 
        flexDirection:"row",
        justifyContent:'center',  
    },
    classTypeNameBox:{
        flex:0.80,
        justifyContent:'space-between',
    },
    solidLine:{
        borderWidth:1,
        borderColor:'black',
    },
    rangeContainer:{
        flex:0.1, 
        flexDirection:"row",
        justifyContent:'center',  
        alignItems:'flex-end',
    },
    rangeBox:{
        flex:0.8,
        justifyContent:'space-between',
        flexDirection:'row'
    },
    locationContainer:{
        flex:0.12,
        flexDirection:"row",
        justifyContent:'center',  
    },
    locationBox:{
        flex:.80,
        justifyContent:'flex-end'
    }
})

export default editClassStyles;