import {StyleSheet} from 'react-native'

const postStyle = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#f2f2f2',
        position:'relative',
    },
    navBar:{
        position:'relative',
        flex:0.15,
        width:'100%',
        flexDirection:'row',
        alignItems:"center",
    },
    post:{
        position:'relative',
        flex:0.1,
        width:'100%',
        backgroundColor:'white',
        alignItems:'center'
    },
    subject:{
        width:'85%',
        height:'100%',
        flexDirection:'row'
    },
    leftSubject:{
        width:'80%', 
        height:'100%', 
        flexDirection:'row',
        alignItems:'center'
    },
    rightSubject:{
        width:'20%', 
        height:'100%', 
        justifyContent:'center',
        alignItems:'center'
    },
    line:{
        borderWidth:0.5,
        borderColor:'black',
        position:'relative',
    },
    questionBox:{
        display:'flex',
        position:'relative',
        minHeight:'5%',
        height:'auto',
        width:'100%',
        backgroundColor:'white',
        alignItems:'center'
    },
    question:{
        width:'85%',
        minHeight:'5%',
        height:'auto',
        justifyContent:'center'
    },
    attachmentBox:{
        position:"relative",
        width:"100%",
        minHeight:0,
    },
    responseContainer:{
        position:'relative',
        width:'100%',
        minHeight:'7%',
        height:'auto',
        top:15,
        alignItems:'center'
    },
    responseBox:{
        position:'relative',
        width:'90%',
        minHeight:'7%',
        height:'auto',
        backgroundColor:'white',
        borderRadius:10,
        flexDirection:'row',
        alignItems:'center'
    },
    repliesContainer:{
        position:'relative',
        width:'100%',
        flex:1,
        top:30,
        marginBottom:15,
    },
    scrollBox:{
        flex:0.1,
        alignItems:'center'
    },
    repliesBox:{
        position:'relative',
        minHeight:'10%',
        width:"90%",
        height:'auto',
        backgroundColor:'white',
        borderRadius:10,
        marginBottom:10
    },
    repliesTop:{
        width:"100%",
        height:35,
        flexDirection:'row',
    },
    repliesName:{
        width:'80%',
        height:'100%',
        justifyContent:'center',
        left:10
    },
    repliesVotes:{
        width:'20%',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
    },
    repliesBot:{
        width:"90%",
        minHeight:'10%',
        height:'auto',
        left:10,
    }
})
export default postStyle;