import {StyleSheet} from 'react-native';
import normalize from 'react-native-normalize';


const newPostStyle = StyleSheet.create({
    container:{
        display: "flex",
        height:'100%',
        width:'100%',
        backgroundColor:'#f2f2f2',
        position:'relative',
    },
    navBar:{
        display:'flex',
        position:'relative',
        height:'15%',
        width:'100%',
        alignItems:'center',
        justifyContent:'center',
        marginTop:20
    },
    chooseBar:{
        width:'80%',
        height:'100%',
        position:'relative',
        justifyContent:'center',
    },
    line:{
        borderWidth:0.5,
        borderColor:'black',
        position:'relative',
        top:'3%',
        marginBottom:20
    },
    subjectList:{
        width:'80%',
        height:'100%',
        position:'relative',
    },
    CancelNextContainer:{
        width:'100%',
        height:'10%',
        display:'flex',
        position:'absolute',
        bottom:"5%",
        alignItems:'center'
    },
    CancelNext:{
        position:'relative',
        flexDirection:'row',
        justifyContent:'space-between',
        width:'80%',
        height:'100%',
    },
    cancel: {
        height:'70%',
        width:'45%',
        backgroundColor:'#FFE9CC',
        borderRadius:10,
        justifyContent:"center",
        alignItems:'center'
    },
    next: {
        height:'70%',
        width:'45%',
        backgroundColor:'#DBF7DF',
        borderRadius:10,
        justifyContent:"center",
        alignItems:'center'
    },
    iconview:{
        width:normalize(30),
        height:normalize(30),
        marginRight:normalize(20),
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        // backgroundColor:"#FAB"
    },
    lineview:{
        width:normalize(200), 
        paddingTop:normalize(10), 
        left:normalize(45)
    },
    each:{
        flexDirection:'row',
         alignItems:"center"
    },
    subjectname:{
        fontSize:normalize(15),
        fontFamily:"SFProDisplay-Regular"
    },
    EP:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#7f7f7f"
    },
    PS:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#00AEEF"
    },
    BC:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#4CD964"
    },
    DS:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#FF3B30"
    },
    AC:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#FF9500"
    },
    ADI:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#FFCF00"
    },
    PJ:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#007AFF"
    },
    WD:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#C69C6D"
    },
    SA:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(25),
        color:"#5856D6"
    },
})
export default newPostStyle;