import {StyleSheet} from 'react-native'
import normalize from 'react-native-normalize';


const markStyles = StyleSheet.create({
    safearea:{
        width:"100%",
        height:"100%"
    },
    navBar:{
       width:'100%',
       height:"7%",
        flexDirection:"row",
        alignItems:'center',
    },
    subjectBar:{
        height:normalize(90),
        marginTop:normalize(10),
        flexDirection:'row',
        justifyContent:"center",
        // backgroundColor:"#FAB"
    },
    subject:{
        flex:0.85,
        flexDirection:'row',
        alignItems:'center'
    },
    progressBar:{
        flex:0.20,
        marginTop:normalize(25),
        flexDirection:'row',
        justifyContent:'center'
    },
    progressBG:{
        flex:0.8,
        backgroundColor:"rgba(255,255,255,0.4)",
        borderRadius:normalize(20),
        flexDirection:'row',
        justifyContent:'center',

    },
    progress:{
        flex:0.8,
        flexDirection:'row',

    },
    editBar:{
        flex:0.09,
        flexDirection:'row',
        justifyContent:'center',
        marginTop:20,
    },
    edit:{
        flex:0.8,
        flexDirection:'row',
        height:normalize(55)
    },
    editboxes:{
        flex:0.95,
        backgroundColor:'white',
        borderRadius:10,
        justifyContent:'center',
        alignItems:'center',

    },
    gradeBox:{
        top:normalize(30),
        flex:0.58,
        backgroundColor:"rgba(255,255,255,0.4)",
        flexDirection:'row',
        justifyContent:'center'
    },
    inputs:{
        flex:0.90,
    },
    scrollview:{
        // backgroundColor:"#FAB"
    },
    inputTitleRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        top:normalize(15),
        marginBottom:normalize(30),
    },
    cancel:{
       
    },
    cancel1:{
        height:20, 
        width:20, 
        backgroundColor:'red', 
        borderRadius:40,
        marginRight:10,
        top:5
    },
    inputRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        top:10,
        marginBottom:30,
    },
    inputTitle:{
        fontSize:15,
        color:'grey'
    },
    markName:{
        fontSize:25,
    },
    PS:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#00AEEF"
    },
    BC:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#4CD964"
    },
    DS:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#FF3B30"
    },
    AC:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#FF9500"
    },
    ADI:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#FFCF00"
    },
    PJ:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#007AFF"
    },
    WD:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#C69C6D"
    },
    SA:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(60),
        color:"#5856D6"
    },
    A:{
        fontFamily:"SFProDisplay-Medium",
        fontSize:normalize(40),
        color:"#4CD964"
    },
    
})

export default markStyles